# Generated by Django 2.2.5 on 2022-05-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default=False, max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(default=False, max_length=20)),
                ('assets', models.IntegerField()),
                ('regdata', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('role', models.IntegerField()),
                ('gend', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='vertify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=10)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
